#ifndef HAL_MOTORDRIVER_MOTORDRIVER_CONFIG_H_
#define HAL_MOTORDRIVER_MOTORDRIVER_CONFIG_H_




/*Motor 1*/
#define MOTION_MOTOR_ONE_PORT GPIO_A
#define MOTION_MOTOR_ONE_PORT GPIO_A

#define MOTION_MOTOR_ONE_PIN_1 PIN3
#define MOTION_MOTOR_ONE_PIN_2 PIN4


/* Motor 2 */
#define MOTION_MOTOR_TWO_PORT GPIO_A
#define MOTION_MOTOR_TWO_PORT GPIO_A

#define MOTION_MOTOR_TWO_PIN_1 PIN5
#define MOTION_MOTOR_TWO_PIN_2 PIN6


/*Motor 3*/
#define MOTION_MOTOR_THREE_PORT GPIO_A
#define MOTION_MOTOR_THREE_PORT GPIO_A

#define MOTION_MOTOR_THREE_PIN_1 PIN7
#define MOTION_MOTOR_THREE_PIN_2 PIN8

/*Motor 4*/
#define MOTION_MOTOR_FOUR_PORT GPIO_B
#define MOTION_MOTOR_FOUR_PORT GPIO_B

#define MOTION_MOTOR_FOUR_PIN_1 PIN6
#define MOTION_MOTOR_FOUR_PIN_2 PIN7


#endif /* HAL_MOTORDRIVER_MOTORDRIVER_CONFIG_H_ */
