#ifndef HAL_ULTRASONIC_ULTRASONIC_CONFIG_H_
#define HAL_ULTRASONIC_ULTRASONIC_CONFIG_H_



#define TIMER_CLK 1
#define FCPU 16

#define READING_NO 10
#define US_NUMBER 4
#define US_TIMERS {TIMER2,TIMER2, TIMER2, TIMER2}

#define US_ECHO_PORTS {PORT_A, PORT_A, PORT_A, PORT_A}
#define US_CHANNEL_PINS {PIN_0, PIN_1, PIN_2, PIN_3}
#define US_CHANNELS {CH1, CH2, CH3, CH4}

#define US_TRIGGER_PORTS {PORT_B, PORT_B, PORT_B, PORT_B}
#define US_TRIGGERS_PINS {PIN_0, PIN_1, PIN_5, PIN_6}



#endif /* HAL_ULTRASONIC_ULTRASONIC_CONFIG_H_ */
