/* LIB */
#include "BIT_MATH.h"
#include "STD_TYPES.h"

/* MCAL */
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "NVIC_interface.h"
#include "SYSTICK_interface.h"
#include "TIMERx_interface.h"



#include "MotorDriver_config.h"
#include "MotorDriver_interface.h"
void H_MotorDriver_voidInit(void) {
	MRCC_voidEnableClock(RCC_APB1,APB1_TIM2EN);
	MTIMERx_voidInit();
	MTIMERx_voidPWMSetup(TIMER2,CH2);

	// Configure Control Pins for direction control
	MGPIO_voidSetPinMode(MOTION_MOTOR_ONE_PORT, MOTION_MOTOR_ONE_PIN_1, OUTPUT_SPEED_10MHZ_PP);
	MGPIO_voidSetPinMode(MOTION_MOTOR_ONE_PORT, MOTION_MOTOR_ONE_PIN_2, OUTPUT_SPEED_10MHZ_PP);
	MGPIO_voidSetPinMode(GPIO_A, MOTOR_1_EN, OUTPUT_SPEED_10MHZ_AFOD);

	MGPIO_voidSetPinMode(MOTION_MOTOR_TWO_PORT, MOTION_MOTOR_TWO_PIN_1, OUTPUT_SPEED_10MHZ_PP);
	MGPIO_voidSetPinMode(MOTION_MOTOR_TWO_PORT, MOTION_MOTOR_TWO_PIN_2, OUTPUT_SPEED_10MHZ_PP);

	MGPIO_voidSetPinMode(MOTION_MOTOR_THREE_PORT, MOTION_MOTOR_THREE_PIN_1, OUTPUT_SPEED_10MHZ_PP);
	MGPIO_voidSetPinMode(MOTION_MOTOR_THREE_PORT, MOTION_MOTOR_THREE_PIN_2, OUTPUT_SPEED_10MHZ_PP);

	MGPIO_voidSetPinMode(MOTION_MOTOR_FOUR_PORT, MOTION_MOTOR_FOUR_PIN_1, OUTPUT_SPEED_10MHZ_PP);
	MGPIO_voidSetPinMode(MOTION_MOTOR_FOUR_PORT, MOTION_MOTOR_FOUR_PIN_2, OUTPUT_SPEED_10MHZ_PP);
	MNVIC_voidEnableInterrupt(28);
}



void H_MotorDriver_voidForward(void) {
	MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 55000);
			MSTK_voidSetBusyWait(500);
			MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 45000);
				MSTK_voidSetBusyWait(500);
				MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 35000);
					MSTK_voidSetBusyWait(500);
					MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 25000);
						MSTK_voidSetBusyWait(500);
						MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 15000);
							MSTK_voidSetBusyWait(500);
							MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 5000);
								MSTK_voidSetBusyWait(500);
								MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 0);
									MSTK_voidSetBusyWait(500);

	//MGPIO_voidSetPinValue(GPIO_A, MOTOR_1_EN, GPIO_HIGH);

	MGPIO_voidSetPinValue(MOTION_MOTOR_ONE_PORT, MOTION_MOTOR_ONE_PIN_1, GPIO_LOW);
	MGPIO_voidSetPinValue(MOTION_MOTOR_ONE_PORT, MOTION_MOTOR_ONE_PIN_2, GPIO_HIGH);

	MGPIO_voidSetPinValue(MOTION_MOTOR_TWO_PORT, MOTION_MOTOR_TWO_PIN_1, GPIO_LOW);
	MGPIO_voidSetPinValue(MOTION_MOTOR_TWO_PORT, MOTION_MOTOR_TWO_PIN_2, GPIO_HIGH);

	MGPIO_voidSetPinValue(MOTION_MOTOR_THREE_PORT, MOTION_MOTOR_THREE_PIN_1, GPIO_LOW);
	MGPIO_voidSetPinValue(MOTION_MOTOR_THREE_PORT, MOTION_MOTOR_THREE_PIN_2, GPIO_HIGH);

	MGPIO_voidSetPinValue(MOTION_MOTOR_FOUR_PORT, MOTION_MOTOR_FOUR_PIN_1, GPIO_LOW);
	MGPIO_voidSetPinValue(MOTION_MOTOR_FOUR_PORT, MOTION_MOTOR_FOUR_PIN_2, GPIO_HIGH);

}


void H_MotorDriver_voidStop(void){


	MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 0);
			MSTK_voidSetBusyWait(3000);
			MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 50000);
				MSTK_voidSetBusyWait(3000);
				MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 15000);
					MSTK_voidSetBusyWait(3000);
					MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 25000);
						MSTK_voidSetBusyWait(3000);
						MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 35000);
							MSTK_voidSetBusyWait(3000);
							MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 45000);
								MSTK_voidSetBusyWait(3000);
								MTIMERx_voidSetPWMDuty(TIMER2 , CH2 , 59999);
									MSTK_voidSetBusyWait(3000);

	MGPIO_voidSetPinValue(MOTION_MOTOR_ONE_PORT, MOTION_MOTOR_ONE_PIN_1, GPIO_LOW);
	MGPIO_voidSetPinValue(MOTION_MOTOR_ONE_PORT, MOTION_MOTOR_ONE_PIN_2, GPIO_LOW);

	MGPIO_voidSetPinValue(MOTION_MOTOR_TWO_PORT, MOTION_MOTOR_TWO_PIN_1, GPIO_LOW);
	MGPIO_voidSetPinValue(MOTION_MOTOR_TWO_PORT, MOTION_MOTOR_TWO_PIN_2, GPIO_LOW);

	MGPIO_voidSetPinValue(MOTION_MOTOR_THREE_PORT, MOTION_MOTOR_THREE_PIN_1, GPIO_LOW);
	MGPIO_voidSetPinValue(MOTION_MOTOR_THREE_PORT, MOTION_MOTOR_THREE_PIN_2, GPIO_LOW);

	MGPIO_voidSetPinValue(MOTION_MOTOR_FOUR_PORT, MOTION_MOTOR_FOUR_PIN_1, GPIO_LOW);
	MGPIO_voidSetPinValue(MOTION_MOTOR_FOUR_PORT, MOTION_MOTOR_FOUR_PIN_2, GPIO_LOW);



}
