#ifndef SSD_CONFIG_H_
#define SSD_CONFIG_H_

#define FIRST_SSD_PORT 			GPIO_A
#define SECOND_SSD_PORT			GPIO_B

#define SSD_ENABLE_PORT 		GPIO_B

#define NUMBER_OF_SSD			TWO



#define FIRST_SSD_TYPE		COMMON_CATHODE
#define SECOND_SSD_TYPE		COMMON_CATHODE
#define THIRD_SSD_TYPE
#define FOURTH_SSD_TYPE
#define FIFTH_SSD_TYPE
#define SIXTH_SSD_TYPE

#define FIRST_SSD_ENABLE 	PIN3
#define SECOND_SSD_ENABLE 	PIN4
#define THIRD_SSD_ENABLE
#define FOURTH_SSD_ENABLE
#define FIFTH_SSD_ENABLE
#define SIXTH_SSD_ENABLE

#endif
