#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_

/* Options
* GPIO_MODE_INPUT
* GPIO_MODE_OUTPUT
* GPIO_MODE_ALT_FUNCTION
* GPIO_MODE_ANALOG
*/
#define GPIO_PIN_MODE_A0  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A1  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A2  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A3  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A4  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A5  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A6  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A7  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A8  GPIO_MODE_INPUT
#define GPIO_PIN_MODE_A9  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A10 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A11 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_A12 GPIO_MODE_OUTPUT

#define GPIO_PIN_MODE_B0  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B1  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B5  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B6  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B7  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B8  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B9  GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B10 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B11 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B12 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B13 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B14 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_B15 GPIO_MODE_OUTPUT

#define GPIO_PIN_MODE_C13 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_C14 GPIO_MODE_OUTPUT
#define GPIO_PIN_MODE_C15 GPIO_MODE_OUTPUT

#endif
